//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderDetails
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual Tbl_Order Tbl_Order { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
