//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Order()
        {
            this.Tbl_OrderDetails = new HashSet<Tbl_OrderDetails>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int MemberId { get; set; }
        public decimal Payment { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Tbl_Member Tbl_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderDetails> Tbl_OrderDetails { get; set; }
    }
}
